sonata_admin:

    templates:
        # other configuration options
        search:              '@SonataAdmin/Core/search.html.twig'
        list:                       '@SonataAdmin/CRUD/list.html.twig'
        action:                     '@SonataAdmin/CRUD/action.html.twig'
        select:                     '@SonataAdmin/CRUD/list__select.html.twig'
        list_block:                 '@SonataAdmin/Block/block_admin_list.html.twig'
        short_object_description:   '@SonataAdmin/Helper/short-object-description.html.twig'
        batch:                      '@SonataAdmin/CRUD/list__batch.html.twig'
        inner_list_row:             '@SonataAdmin/CRUD/list_inner_row.html.twig'
        base_list_field:            '@SonataAdmin/CRUD/base_list_field.html.twig'
        pager_links:                '@SonataAdmin/Pager/links.html.twig'
        pager_results:              '@SonataAdmin/Pager/results.html.twig'
        edit:              '@SonataAdmin/CRUD/edit.html.twig'
        tab_menu_template: '@SonataAdmin/Core/tab_menu_template.html.twig'
        search_result_block: '@SonataAdmin/Block/block_search_result.html.twig'
        #show:'@App/Admin/display_client.html.twig'
        show: '@SonataAdmin/CRUD/show.html.twig'
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
            -
              position: right
              type: sonata.block.service.text
              settings:
                  content: >
                      <h2>Welcome to the Sonata Admin</h2>
                      <p>This is a <code>sonata.block.service.text</code> from the Block
                      Bundle, you can create and add new block in these area by configuring
                      the <code>sonata_admin</code> section.</p> <br/> For instance, here
                      a RSS feed parser (<code>sonata.block.service.rss</code>):

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.block.service.text:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]