<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.wQGT_.q' shared service.

return $this->privates['.service_locator.wQGT_.q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'breadcrumbs' => array('services', 'white_october_breadcrumbs', 'getWhiteOctoberBreadcrumbsService.php', true),
    'paginator' => array('services', 'knp_paginator', 'getKnpPaginatorService.php', true),
    'repository' => array('privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService.php', true),
));
