controllers:
  resource: ../../src/Controller/
  type: annotation

rest_controller:
  resource: ../../src/Controller/Api/
  prefix: /api
  type: annotation

app_api:
  resource: ../../src/Controller/Api/
  type: annotation