<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.GVTFkKf' shared service.

return $this->privates['.service_locator.GVTFkKf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'breadcrumbs' => array('services', 'white_october_breadcrumbs', 'getWhiteOctoberBreadcrumbsService.php', true),
));
