#index:
 # path: /
  #controller: App\Controller\ArticleController::homepage

#app_lucky_number:
 # path: /lucky/number
  #controller: App\Controller\LuckyController::number

mgilet_notification:
  resource: "@MgiletNotificationBundle/Controller/"
  prefix: /notifications