<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Twig\AppRuntime' shared autowired service.

include_once $this->targetDirs[3].'/vendor/twig/twig/src/Extension/RuntimeExtensionInterface.php';
include_once $this->targetDirs[3].'/src/Twig/AppRuntime.php';

return $this->privates['App\Twig\AppRuntime'] = new \App\Twig\AppRuntime();
