<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_elastica.config_manager' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Configuration/ManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Configuration/ConfigManager.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Configuration/Source/SourceInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Configuration/Source/ContainerSource.php';

return $this->services['fos_elastica.config_manager'] = new \FOS\ElasticaBundle\Configuration\ConfigManager(array(0 => new \FOS\ElasticaBundle\Configuration\Source\ContainerSource(array('app' => array('elasticsearch_name' => 'app', 'reference' => ($this->services['fos_elastica.index.app'] ?? $this->load('getFosElastica_Index_AppService.php')), 'name' => 'app', 'settings' => array(), 'type_prototype' => array(), 'use_alias' => false)))));
