<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGQJ05Eg\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGQJ05Eg/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGQJ05Eg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGQJ05Eg\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGQJ05Eg\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'GQJ05Eg',
    'container.build_id' => 'e50917ea',
    'container.build_time' => 1554466842,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerGQJ05Eg');
