<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.xmP46SL' shared service.

return $this->privates['.service_locator.xmP46SL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'breadcrumbs' => array('services', 'white_october_breadcrumbs', 'getWhiteOctoberBreadcrumbsService.php', true),
    'post' => array('privates', '.errored..service_locator.xmP46SL.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.xmP46SL": it references class "App\\Entity\\Post" but no such service exists.'),
    'repository' => array('privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService.php', true),
));
