<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_elastica.pager_provider_registry' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/ContainerAwareInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/ContainerAwareTrait.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Provider/PagerProviderRegistry.php';

$this->services['fos_elastica.pager_provider_registry'] = $instance = new \FOS\ElasticaBundle\Provider\PagerProviderRegistry(array());

$instance->setContainer($this);

return $instance;
