<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'white_october_breadcrumbs.helper' shared service.

include_once $this->targetDirs[3].'/vendor/whiteoctober/breadcrumbs-bundle/WhiteOctober/BreadcrumbsBundle/Templating/Helper/BreadcrumbsHelper.php';

return $this->services['white_october_breadcrumbs.helper'] = new \WhiteOctober\BreadcrumbsBundle\Templating\Helper\BreadcrumbsHelper(($this->services['templating'] ?? $this->getTemplatingService()), ($this->services['white_october_breadcrumbs'] ?? $this->load('getWhiteOctoberBreadcrumbsService.php')), $this->parameters['white_october_breadcrumbs.options']);
